---

- name: Install Java
  apt: "name={{ java_package }} state=present"
  when: use_existing_java is defined and use_existing_java == False

- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home != ''

- name: Java | Source environment variables
  shell: source /etc/profile
  args:
    executable: /bin/bash